project:
  type: website
  output-dir: docs
  
website:
  favicon: favicon.png
  title: "James Coughlan"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - projects.qmd
      - posts.qmd
      - cv.qmd
  page-footer:
    right: "Unless explicitly stated, any opinions expressed here are not those of my employers, co-authors or collaborating organisations. Any errors, ommissions or oversights are mine alone."
    left: "&copy; Copyright 2024, James Coughlan"

format:
  html:
    theme: 
    - litera
    - styles.scss
    toc: false

editor: source

