project:
  type: website
  output-dir: docs
  
website:
  title: "James Coughlan"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - projects.qmd
      - posts.qmd
      - cv.qmd
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2024, James Coughlan"

format:
  html:
    theme: 
    - litera
    - styles.scss
    toc: false

editor: source

