---
title: "Research"
---

### 2024

-   Coughlan, James; Hewett, Timothy; Pla Farriol, Eduard. [The impact of Brexit on research and development](https://repositori.upf.edu/handle/10230/60933). Published Masters Thesis, UPF e-Repositori. 2024

### 2023

### 2022

-   Duane B, **Coughlan J**, Quintonez C, Johnston B, Fisher J, Pasdeki-Clewer E, et al. [Sustainability: The Need to Transform Oral Health Systems](https://link.springer.com/chapter/10.1007/978-3-031-07999-3_12). In: Duane B, editor. Sustainable Dentistry: Making a Difference \[Internet\]. Cham: Springer International Publishing; 2022. p. 213–36.

### 2021

-   **Coughlan J**, Timuş D, Crnic T, Srdoč D, Halton C, Dragan IF. [Impact of COVID‐19 on dental education in Europe: the students’ perspective](https://onlinelibrary.wiley.com/doi/10.1111/eje.12736). European Journal of Dental Education. 2021;(November):1–9.

-   Duane B, Dixon J, Ambibola G, Aldana C, **Coughlan J**, Henao D, et al. [Embedding environmental sustainability within the modern dental curriculum— Exploring current practice and developing a shared understanding](https://onlinelibrary.wiley.com/doi/10.1111/eje.12631). Eur J Dental Education. 2021 Aug;25(3):541–9.

### 2020

-   **Coughlan J**, Shah S. [The impact of Brexit on oral health](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7662723/). British Dental Journal. 2020;229(9):622–6.

-   Dave M, **Coughlan J**, Patel N, Coulthard P. [The momentum shift towards telemedicine](https://publishing.rcseng.ac.uk/doi/abs/10.1308/rcsfdj.2020.109?download=true&journalCode=fdj). FDJ. 2020 Oct 1;11(4):150–1.

### In Progress

-   **Coughlan J**, Pold A, Gkekas A, Meheus F, Gierth J, Hoffbauer T, Varenne B, Listl S, Pattamatta M. Cost-effective interventions for oral health: A WHO-CHOICE Analysis for 62 countries. 2024.

-   **Coughlan J**, Thomson W, Sutton M. The association between dental expenditure and financial protection in the United Kingdom. 2024.

-   Zaheer K, **Coughlan J.** Utilisation of an emergency dental clinic by the Rohingya refugees in Ukihya, Bangladesh. 2024.

### Conference Contributions

-   **Coughlan J**, Pold A, Gkekas A, Meheus F, Gierth J, Hoffbauer T, Varenne B, Listl S, Pattamatta M. Cost-effective interventions for oral health: A WHO-CHOICE Analysis for 62 countries. Oral Presentation at: University of Pennsylvania Global Oral Health Forum II 2024; Philadelphia, USA

-   **Coughlan J**, Thompson W, Sutton M. The contribution of dental expenditure to poverty. Poster presented at: Summer Scientific Meeting of the British Association for the Study of Community Dentistry 2023; Cork, Ireland.

-   **Coughlan J**, Hegenauer M, Volkmann Z. Embedding sustainability into oral health systems: a complex systems approach. Poster presented at: World Dental Federation (FDI) Sustainability in Dentistry Summit 2023; Online event.
